"""Auditable rule definitions. Add checks here without changing orchestration.

These are reporting cues and narrow textual contradictions, not validated scientific
classifiers. Domain applicability and cautious status language are part of each rule.
"""
from dataclasses import dataclass


@dataclass(frozen=True)
class Check:
    id: str
    label: str
    domain: str
    pattern: str
    category: str
    severity: str
    why: str
    fix: str
    analysis: str


@dataclass(frozen=True)
class PatternRule:
    id: str
    label: str
    domain: str
    pattern: str
    category: str
    severity: str
    status: str
    why: str
    fix: str
    analysis: str


CHECKS = [
    Check("external_validation", "Independent external validation", "predictive",
          r"\bexternal(?:ly)?\b.{0,65}\b(?:cohort|dataset|validation|patients|hospital|institution)\b|"
          r"\bindependent\s+(?:(?:external|test|validation)\s+)?(?:cohort|dataset|patients|hospital|institution)\b",
          "validation", "major", "Internal reuse can leave transportability and performance optimism unresolved.",
          "Identify the independent cohort, provenance, overlap checks, and locked model; otherwise bound the claim.",
          "Evaluate the locked pipeline in a disjoint external cohort; report uncertainty and population differences."),
    Check("confidence_intervals", "Confidence intervals or credible intervals", "quantitative",
          r"\b(?:confidence|credible)\s+intervals?\b|\b95\s*%\s*CI\b",
          "statistics", "moderate", "Point estimates alone do not communicate sampling uncertainty.",
          "Report interval estimates for primary effects and predictive metrics, with their construction and sampling unit.",
          "Estimate uncertainty using an appropriate model or resampling at the independent biological unit."),
    Check("sample_sizes", "Identifiable sample-size statements", "quantitative",
          r"\bn\s*=\s*\d+|\b\d[\d,]*\s+(?:patients?|donors?|participants?|samples?|replicates?)\b",
          "reporting", "major", "The effective sample size determines precision and the strength of the evidence.",
          "State sample sizes by cohort, arm, assay, and biological unit; distinguish cells from donors.",
          "Tabulate inclusion, exclusions, and independent sample counts for each analysis."),
    Check("biological_replicates", "Biological replication units", "quantitative",
          r"\bbiological replicates?\b|\b\d+\s+(?:independent\s+)?(?:donors|patients|animals)\b|\bdonor.level\b",
          "design", "major", "Technical measurements do not automatically provide independent biological replication.",
          "Identify biological and technical replication, their nesting, and group allocation.",
          "Reanalyze uncertainty at the biological replicate level where relevant."),
    Check("train_test_split", "Train/test separation", "predictive",
          r"\b(?:train(?:ing)?.{0,35}(?:test|validation).{0,30}split|split.{0,50}(?:train|test)|nested cross.validation)\b",
          "leakage", "major", "Unclear separation prevents assessment of out-of-sample evaluation.",
          "Document split units and timing relative to preprocessing, feature selection, and tuning.",
          "Re-run a nested evaluation with all fitted steps inside the training partition."),
    Check("grouped_validation", "Grouped or stratified validation", "predictive",
          r"\b(?:grouped|stratified|donor.held.out|patient.held.out|leave.one.(?:donor|patient|cohort).out)\b",
          "leakage", "moderate", "Related samples and imbalanced folds can inflate apparent generalization.",
          "Explain grouping, class balance, patient/cohort separation, and fold construction.",
          "Compare appropriate grouped folds and report fold-level class and cohort composition."),
    Check("random_seed", "Random seeds", "quantitative",
          r"\b(?:random\s+)?seeds?\s*(?:was|were|=|:|of|set to|set at|used)?\s*\d+|\brandom_state\s*=\s*\d+",
          "reproducibility", "minor", "Stochastic procedures may not be reproducible without the random state.",
          "State seeds for stochastic steps or explain why the workflow is deterministic.",
          "Repeat key stochastic steps across seeds and report material variation."),
    Check("code_availability", "Code availability", "general",
          r"\b(?:github\.com|gitlab\.com|code.{0,35}(?:available|unavailable|deposited|released|repository)|software.{0,30}repository)\b",
          "reproducibility", "moderate", "Readers need access to the analysis implementation.",
          "Provide an accessible versioned repository, environment, and execution instructions.",
          "Run the documented pipeline from a clean environment."),
    Check("data_availability", "Data availability and access", "general",
          r"\b(?:GSE\d{3,}|EGAS\d+|phs\d+|data.{0,40}(?:available|unavailable|deposited|accession|access controlled)|controlled.access)\b",
          "reproducibility", "moderate", "Data provenance and access conditions are necessary for independent evaluation.",
          "Give accessions, cohort provenance, access restrictions, and a realistic access procedure.",
          "Verify that the stated accessions and derived artifacts support the reported analyses."),
    Check("multiple_testing", "Multiplicity correction", "testing",
          r"\b(?:Benjamini.Hochberg|Bonferroni|false discovery rate|FDR|Holm|multiple.testing correction|adjusted p.values?)\b",
          "statistics", "major", "Searching many hypotheses can produce false discoveries without a justified error-control strategy.",
          "State the hypothesis family, correction, threshold, and any unadjusted exploratory analyses.",
          "Recompute adjusted results across the actual tested family and report effect sizes."),
    Check("limitations", "Acknowledged limitations", "general",
          r"\b(?:limitation|limitations|limited by|cannot establish|does not establish|may not generalize)\b",
          "interpretation", "minor", "Readers need explicit boundaries on what the study establishes.",
          "Explain design, measurement, cohort, and inference limitations in relation to the main claims.",
          "Assess sensitivity to the most consequential limitation where feasible."),
    Check("calibration", "Predictive calibration", "predictive",
          r"\b(?:calibration|calibrated|Brier score|calibration.slope|calibration.intercept)\b",
          "statistics", "moderate", "Discrimination does not establish the accuracy of predicted probabilities.",
          "If probabilities are used, report calibration; otherwise explain why it is not applicable.",
          "Assess calibration plots, slope/intercept, and an appropriate proper scoring rule externally."),
    Check("metric_context", "Discrimination metrics and class prevalence", "predictive",
          r"\b(?:class prevalence|positive.class prevalence|class balance|precision.recall baseline|event prevalence)\b",
          "statistics", "moderate", "AUROC and AUPRC answer different questions and depend differently on class distribution.",
          "Define the positive class and explain metric choice, prevalence, and uncertainty.",
          "Report complementary discrimination measures and prevalence-aware baselines."),
    Check("baseline_models", "Baseline models", "predictive",
          r"\b(?:baseline model|baseline predictor|clinical.only|simple baseline|benchmark model)\b",
          "validation", "moderate", "Incremental predictive value is unclear without meaningful comparators.",
          "Describe fair simple and clinical baselines with identical validation boundaries.",
          "Compare against prespecified baseline models on the same held-out samples."),
    Check("confounding", "Confounder assessment", "quantitative",
          r"\b(?:adjusted for|confound\w*|covariate adjustment)\b",
          "confounding", "moderate", "Observed differences may reflect cohort composition rather than the proposed biology.",
          "Identify candidate confounders, including cancer type, treatment, batch, platform, and ascertainment.",
          "Use justified stratification, adjustment, or negative controls; report overlap and residual limitations."),
    Check("sensitivity", "Sensitivity and robustness analyses", "quantitative",
          r"\b(?:sensitivity analys[ei]s|robustness analys[ei]s|alternative preprocessing|alternative pipeline)\b",
          "validation", "moderate", "A conclusion may depend on one preprocessing or modeling choice.",
          "Document sensitivity to defensible preprocessing, model, and threshold choices.",
          "Repeat primary analyses under justified alternatives and report stability of conclusions."),
    Check("null_models", "Null model or permutation rationale", "testing",
          r"\b(?:null model|permutation|exchangeability|negative.control distribution)\b",
          "statistics", "moderate", "A poorly specified null can misrepresent the evidence against chance.",
          "Explain the null hypothesis, preserved structure, exchangeability, and permutation count where applicable.",
          "Use nulls or permutations that respect donor, cohort, batch, and feature dependence."),
    Check("software_versions", "Software and environment versions", "general",
          r"\b(?:version\s+\d|v\d+\.\d+|environment\.ya?ml|requirements\.txt|renv\.lock|container digest)\b",
          "reproducibility", "minor", "Unspecified software versions hinder exact reproduction.",
          "Provide software versions and a pinned environment or container.",
          "Check that a clean installation reproduces a representative result."),
    Check("pseudobulk", "Donor-aware single-cell inference", "single_cell",
          r"\b(?:pseudobulk|mixed.effects?|donor.level|patient.level|hierarchical model)\b",
          "single_cell", "major", "Cells from the same donor share biological and technical variation.",
          "Explain the independent unit and donor-aware model for each inferential test.",
          "Compare donor-level pseudobulk or a justified hierarchical model to the primary analysis."),
    Check("donor_cell_balance", "Donor and cell-number balance", "single_cell",
          r"\b(?:cells per donor|cell.number imbalance|donor imbalance|downsampl\w*|donor composition)\b",
          "single_cell", "moderate", "Unequal cell contributions can dominate pooled results.",
          "Report donors and cell counts by condition, batch, and cluster.",
          "Assess robustness to balanced sampling and donor-level weighting."),
    Check("batch_platform", "Batch, platform, and cancer-type confounding", "single_cell",
          r"\b(?:batch.{0,25}(?:confound|balance|covariate)|platform.{0,25}(?:confound|balance)|cancer.type.{0,25}(?:confound|adjust))",
          "confounding", "major", "Technical or disease composition can align with the biological contrast.",
          "Show cross-tabulations of condition with donor, batch, platform, and cancer type.",
          "Test contrasts within comparable strata and assess sensitivity to adjustment and integration."),
    Check("cluster_stability", "Cluster stability", "single_cell",
          r"\b(?:cluster stability|clustering stability|resolution sensitivity|cluster robustness)\b",
          "single_cell", "moderate", "An unstable clustering can undermine downstream interpretation.",
          "Explain how clustering resolution and algorithm dependence were assessed.",
          "Compare cluster assignments across resolutions, seeds, and plausible preprocessing choices."),
    Check("annotation_robustness", "Annotation and reference robustness", "single_cell",
          r"\b(?:alternative annotations?|alternative (?:reference|atlas)|reference.atlas sensitivity|annotation robustness)\b",
          "single_cell", "moderate", "Reference choice and reused marker genes can predetermine the interpretation.",
          "State annotation provenance and separate labeling evidence from validation evidence.",
          "Repeat key contrasts with alternative annotations or reference atlases and independent markers."),
    Check("doublets", "Doublet handling", "single_cell", r"\b(?:doublets?|Scrublet|DoubletFinder)\b",
          "single_cell", "moderate", "Doublets can mimic hybrid states or alter cell abundance.",
          "Describe doublet detection, rates, thresholds, and limitations.",
          "Assess whether candidate states and conclusions survive reasonable doublet filters."),
    Check("ambient_rna", "Ambient RNA assessment", "single_cell", r"\b(?:ambient RNA|SoupX|CellBender|decontX)\b",
          "single_cell", "moderate", "Ambient transcripts can distort marker expression and state assignments.",
          "Explain contamination assessment and whether correction was appropriate.",
          "Test whether key markers persist under a defensible contamination correction."),
    Check("integration", "Integration artifacts and leakage", "single_cell",
          r"\b(?:integration.{0,40}(?:artifact|leakage|held.out)|unintegrated|without integration)\b",
          "leakage", "moderate", "Integration may erase biology or transfer evaluation information into training.",
          "Document integration inputs, split timing, and comparisons with unintegrated analyses.",
          "Evaluate held-out donors without joint fitting and compare unintegrated biological contrasts."),
    Check("composition", "Differential abundance and compositional effects", "single_cell",
          r"\b(?:compositional|differential abundance|scCODA|Milo)\b",
          "single_cell", "moderate", "Cell fractions are interdependent and sampled within donors.",
          "For abundance claims, justify the donor-level model, denominators, and compositional assumptions.",
          "Use donor-aware differential abundance analysis and evaluate denominator sensitivity."),
    Check("thresholds", "Threshold sensitivity", "single_cell",
          r"\b(?:threshold sensitivity|alternative thresholds?|QC sensitivity|quality.control thresholds?)\b",
          "single_cell", "moderate", "Filtering and classification thresholds can select the apparent signal.",
          "Report thresholds and their rationale, including post hoc changes.",
          "Assess primary conclusions over a reasonable prespecified threshold range."),
    Check("perturbation_efficiency", "Perturbation efficiency", "perturbation",
          r"\b(?:perturbation efficiency|editing efficiency|knockdown efficiency|on.target efficiency)\b",
          "perturbation", "major", "A nominal intervention does not establish an effective molecular perturbation.",
          "Quantify on-target perturbation at the relevant molecular level and time point.",
          "Relate phenotypes to measured perturbation efficiency."),
    Check("guides", "Multiple guides and guide-level consistency", "perturbation",
          r"\b(?:multiple guides|[2-9]\s+guides per gene|guide.level consistency|guide concordance)\b",
          "perturbation", "major", "A single guide phenotype may reflect efficiency or off-target effects.",
          "Report guide counts, guide-level effects, concordance, and aggregation rules.",
          "Validate with independent guides and an orthogonal intervention or rescue where feasible."),
    Check("moi", "MOI assumptions", "perturbation",
          r"\b(?:MOI|multiplicity of infection|non.viral delivery|transfection)\b",
          "perturbation", "moderate", "Delivery and multiplicity assumptions affect attribution of perturbations.",
          "Specify delivery, MOI where applicable, assignment, and multiple-perturbation handling.",
          "Check sensitivity to multi-guide cells and assignment thresholds."),
    Check("toxicity", "Essential-gene and toxicity confounding", "perturbation",
          r"\b(?:toxicity|essential.gene|viability|cell.cycle confounding)\b",
          "perturbation", "major", "General fitness effects may masquerade as pathway-specific mechanisms.",
          "Separate specific phenotypes from viability, stress, and essential-gene effects.",
          "Compare viability-matched controls and evaluate stress/cell-cycle signatures."),
    Check("off_targets", "Off-target assessment", "perturbation", r"\b(?:off.target|rescue experiment)\b",
          "perturbation", "moderate", "Guide-associated effects may not be specific to the intended target.",
          "Describe off-target mitigation and independent validation.",
          "Use concordant independent perturbations and a suitable rescue or orthogonal assay."),
    Check("screen_controls", "Positive and negative controls", "perturbation",
          r"\bpositive.{0,45}negative.{0,30}controls?\b|\bnegative.{0,45}positive.{0,30}controls?\b",
          "perturbation", "major", "Screen dynamic range and specificity depend on appropriate controls.",
          "Identify positive, negative, and non-targeting controls and their expected behavior.",
          "Quantify control separation and benchmark screen sensitivity."),
    Check("screen_quality", "Screen QC and replicate concordance", "perturbation",
          r"\b(?:screen quality|replicate concordance|guide coverage|Gini index|screen QC)\b",
          "perturbation", "moderate", "Poor representation or discordant replicates can destabilize screen hits.",
          "Report coverage, library bottlenecks, quality metrics, and replicate agreement.",
          "Test hit stability across replicates and coverage filters."),
    Check("perturbation_model", "Modality and screen-model assumptions", "perturbation",
          r"\b(?:MAGeCK|CRISPRi|CRISPRa|CRISPR KO|base.editing|model assumptions)\b",
          "perturbation", "moderate", "Different modalities and count models have different failure modes.",
          "Specify modality, model, copy-number handling, and limitations relevant to the system.",
          "Evaluate model diagnostics and modality-specific confounders; inspect copy-number effects for KO screens."),
    Check("clinical_use", "Intended clinical use", "biomarker",
          r"\b(?:intended (?:clinical )?use|intended population|clinical decision|use case)\b",
          "clinical", "major", "A predictive association is not yet a clinically actionable use case.",
          "Define the decision, population, setting, comparator, and consequences of error.",
          "Evaluate the proposed use against a relevant clinical baseline."),
    Check("endpoint", "Endpoint definition", "biomarker",
          r"\b(?:endpoint (?:was |is )?defined|endpoint definition|primary endpoint|outcome defined)\b",
          "clinical", "major", "Ambiguous outcomes hinder interpretation and transportability.",
          "Define endpoints, measurement windows, adjudication, and follow-up.",
          "Assess robustness to clinically justified endpoint definitions."),
    Check("ascertainment", "Cohort ascertainment", "biomarker",
          r"\b(?:inclusion criteria|exclusion criteria|consecutive patients|cohort ascertainment|eligibility criteria)\b",
          "clinical", "moderate", "Selection processes can alter apparent performance and applicability.",
          "Describe recruitment, inclusion/exclusion, sampling, and cohort flow.",
          "Compare included and excluded subjects and characterize selection limitations."),
    Check("prevalence_shift", "Population or prevalence shift", "biomarker",
          r"\b(?:prevalence shift|population shift|distribution shift|transportability)\b",
          "clinical", "moderate", "Deployment populations may differ from the development sample.",
          "Describe plausible prevalence and population shifts for the intended use.",
          "Evaluate discrimination, calibration, and decision thresholds across relevant populations."),
    Check("cutoff", "Cutoff selection", "biomarker",
          r"\b(?:prespecified cutoff|pre.specified threshold|cutoff.{0,40}training|threshold.{0,40}training|continuous score)\b",
          "leakage", "major", "Outcome-informed threshold selection can bias reported performance.",
          "State when, where, and how any cutoff was chosen and locked.",
          "Evaluate a training-selected or prespecified threshold in untouched data."),
    Check("treatment_interaction", "Predictive versus prognostic interpretation", "biomarker",
          r"\b(?:treatment interaction|treatment.by.biomarker|prognostic rather than predictive|prognostic association)\b",
          "clinical", "moderate", "Prognostic association alone does not demonstrate differential treatment benefit.",
          "Clarify whether the claim is prognostic or treatment-predictive and justify the distinction.",
          "For treatment-benefit claims, assess a justified treatment-by-biomarker interaction in an appropriate design."),
    Check("subgroups", "Subgroup stability", "biomarker",
          r"\b(?:subgroup stability|subgroup analys[ei]s|stratified performance)\b",
          "clinical", "moderate", "Aggregate performance can hide clinically important heterogeneity.",
          "Describe justified subgroup analyses, sizes, uncertainty, and exploratory status.",
          "Estimate subgroup performance without overstating underpowered differences."),
    Check("missingness", "Missing data", "biomarker",
          r"\b(?:missing data|missingness|imputation|complete.case|no missing values)\b",
          "statistics", "moderate", "Missingness and its handling can introduce selection or leakage.",
          "Describe missingness by variable and cohort, assumptions, and fitting boundaries for imputation.",
          "Evaluate sensitivity to plausible missing-data mechanisms and alternative handling."),
    Check("censoring", "Time-to-event and censoring methods", "survival",
          r"\b(?:censoring|censored|competing risks|proportional hazards)\b",
          "statistics", "major", "Time-to-event results depend on follow-up, censoring, and model assumptions.",
          "Describe censoring, time origin, follow-up, competing risks, and model diagnostics.",
          "Check proportional hazards or relevant assumptions and report follow-up and event counts."),
    Check("clinical_utility", "Clinical utility", "biomarker",
          r"\b(?:decision.curve|net benefit|clinical utility|utility evaluation)\b",
          "clinical", "moderate", "Statistical significance does not establish useful clinical decisions.",
          "Bound clinical claims and distinguish utility evaluation from association.",
          "Where appropriate, evaluate net benefit and consequences against standard care."),
]

PATTERNS = [
    PatternRule("design_confounding", "Condition aligned with batch or platform", "quantitative",
                r"\b(?:platform|batch|cancer.type|condition|response)\b.{0,80}\b(?:remain(?:s)? confounded|(?:perfectly|completely) confounded|confounded with)\b",
                "confounding", "major", "established_issue",
                "When a biological contrast aligns with a technical stratum, its separate contribution may be unidentifiable.",
                "Show condition-by-platform/batch tables and bound conclusions to identifiable comparisons.",
                "Evaluate an independently balanced cohort or within-stratum comparisons where overlap exists; adjustment alone may not identify fully confounded effects."),
    PatternRule("feature_selection_before_split", "Feature selection before splitting", "predictive",
                r"\b(?:select\w*|filter\w*|rank\w*).{0,100}\b(?:genes|features|variables)\b.{0,120}\bbefore\b.{0,45}\b(?:split\w*|cross.validation)\b",
                "leakage", "major", "established_issue",
                "Data-dependent selection using evaluation samples makes the reported evaluation non-independent.",
                "Clarify whether selection used outcomes and evaluation samples; fit all learned selection inside training folds.",
                "Repeat nested evaluation with selection refit using training samples only."),
    PatternRule("test_set_tuning", "Test data used for tuning", "predictive",
                r"\b(?:tun\w*|optimi[sz]\w*|select\w*).{0,65}\b(?:hyperparameters?|parameters?|threshold|cutoff)\b.{0,65}\b(?:test set|test data|test cohort)\b",
                "leakage", "major", "established_issue",
                "Choosing model settings on a test set turns it into development data.",
                "Use inner validation for tuning and retain an untouched evaluation set.",
                "Re-evaluate the locked model in fresh data or a correctly nested design."),
    PatternRule("cohort_reuse", "Discovery and validation cohort reuse", "predictive",
                r"\b(?:same|identical)\s+(?:patient\s+)?(?:cohort|dataset|samples|patients)\b.{0,110}\b(?:discovery|training)\b.{0,60}\bvalidation\b",
                "circularity", "major", "established_issue",
                "Reuse does not establish independent validation and can repeat discovery biases.",
                "Label the analysis as internal reuse and identify independent validation if it exists.",
                "Validate a locked signature or model in a disjoint cohort with overlap checks."),
    PatternRule("cell_pseudoreplication", "Cells treated as independent biological replicates", "single_cell",
                r"\bcells\b.{0,60}\b(?:treated|considered|used|analy[sz]ed)\b.{0,45}\bindependent\b.{0,30}\b(?:replicates|observations|samples)\b",
                "single_cell", "major", "established_issue",
                "Within-donor dependence can understate uncertainty when cells replace donors as independent units.",
                "Report donor nesting and justify the model; distinguish technical observations from biological replicates.",
                "Reanalyze using donor-level pseudobulk or an appropriate hierarchical model."),
    PatternRule("circular_signature", "Signature reused for its own validation", "general",
                r"\b(?:same|identical)\s+(?:marker\s+)?genes\b.{0,150}\b(?:construct\w*|defin\w*|build\w*|select\w*)\b.{0,100}\bvalidat\w*",
                "circularity", "major", "plausible_issue",
                "Reusing defining features as evidence of validity may produce a tautological result.",
                "Separate construction, annotation, and validation features and document any overlap.",
                "Validate using independent features, phenotypes, perturbations, or held-out evidence."),
    PatternRule("causal_overclaim", "Causal or mechanistic wording needs support", "general",
                r"\b(?:prove[sd]?|demonstrat\w*|establish\w*)\b.{0,55}\b(?:causal\w*|causation|mechanis\w*)\b",
                "interpretation", "major", "plausible_issue",
                "A strong causal phrase requires a design that identifies the claimed mechanism or causal effect.",
                "Connect the wording to identifying evidence; if support is associative, use appropriately limited language.",
                "Evaluate perturbation, rescue, temporal ordering, and alternative causal explanations as appropriate."),
    PatternRule("novelty_overclaim", "Absolute novelty claim", "general",
                r"\b(?:first(?:.ever)?|unprecedented|entirely novel)\b.{0,70}\b(?:study|method|model|framework|demonstration|approach)\b",
                "positioning", "moderate", "plausible_issue",
                "Absolute novelty requires a scoped and current literature comparison, which this offline tool cannot verify.",
                "Scope the novelty to a specific contribution and substantiate it with a literature comparison.",
                "Build a comparison table of the closest prior methods, data, evidence, and practical differences."),
    PatternRule("conservation_overclaim", "Similarity or transferability used to claim conservation", "general",
                r"\b(?:similarity|transferability|transfer|transcriptomic)\b.{0,100}\b(?:prov\w*|demonstrat\w*|establish\w*)\b.{0,70}\b(?:conserv\w*|shared regulation)\b",
                "interpretation", "major", "plausible_issue",
                "Transcriptomic similarity or transfer alone does not establish a conserved regulatory mechanism.",
                "Separate shared predictive structure from evidence of shared regulation.",
                "Test specific regulatory predictions with orthogonal perturbations across the relevant tissues or cohorts."),
    PatternRule("latent_overinterpretation", "Latent structure given causal meaning", "single_cell",
                r"\b(?:UMAP|latent dimension|cluster)\b.{0,100}\b(?:prove[sd]?|establish\w*)\b.{0,50}\b(?:mechanism|lineage|causal)\b",
                "interpretation", "major", "plausible_issue",
                "An embedding or cluster is a representation; it is not itself an identifying mechanistic experiment.",
                "Describe the observed structure and state the independent evidence needed for the interpretation.",
                "Test stability and use independent lineage, temporal, or perturbational evidence."),
]
